# Generated by Django 3.0.5 on 2020-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('anons', models.TextField(verbose_name='Анонс')),
                ('image', models.ImageField(upload_to='media/banners')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
