# Generated by Django 3.0.5 on 2020-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0004_banner_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
