# Generated by Django 3.0.5 on 2020-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0009_auto_20200409_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
