# Generated by Django 3.0.5 on 2020-04-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0010_auto_20200409_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Принадлежность'},
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.CharField(default=1, max_length=1, verbose_name='Очередность вывода'),
            preserve_default=False,
        ),
    ]
