# Generated by Django 3.0.5 on 2020-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0011_auto_20200412_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='catalog/products'),
            preserve_default=False,
        ),
    ]
