# Generated by Django 3.0.5 on 2020-04-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='obuv.Size', verbose_name='Размер'),
        ),
    ]
