# Generated by Django 3.0.5 on 2020-04-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0014_auto_20200412_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sizes', to='obuv.Genre', verbose_name='Принадлежность'),
        ),
    ]
