# Generated by Django 3.0.5 on 2020-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0015_auto_20200416_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='catalog/products', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, upload_to='catalog/products', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='anons',
            field=models.TextField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='catalog/products', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='catalog/products', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='catalog/products', verbose_name='Изображение 3'),
        ),
    ]
