# Generated by Django 3.0.5 on 2020-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0018_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_sale',
            field=models.BooleanField(default=False, verbose_name='Виден в топ продаж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_page',
            field=models.BooleanField(default=False, verbose_name='Виден на главной в продукции'),
        ),
    ]
