# Generated by Django 3.0.5 on 2020-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0019_auto_20200426_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Партнеры')),
                ('brend_logo', models.ImageField(blank=True, upload_to='partners', verbose_name='Лого партнера')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'verbose_name_plural': 'Партнер',
            },
        ),
    ]
