# Generated by Django 3.0.5 on 2020-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0020_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на сайт партнера'),
        ),
    ]
