# Generated by Django 3.0.5 on 2020-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0021_partner_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Принадлежности', 'verbose_name_plural': 'Принадлежность'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_in',
            field=models.BooleanField(default=True, verbose_name='Присутствует в каталоге'),
        ),
    ]
