# Generated by Django 3.0.5 on 2020-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0023_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minibanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название минибаннера')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст баннера')),
                ('link', models.URLField(blank=True, verbose_name='сслыка на публикацию')),
                ('main_page', models.BooleanField(default=False, verbose_name='Опубликлован на главной')),
                ('public_all', models.BooleanField(default=False, verbose_name='Опубликован в блоке анонсов')),
            ],
            options={
                'verbose_name': 'Минибаннер на главной',
                'verbose_name_plural': 'Минибаннеры',
            },
        ),
    ]
