# Generated by Django 3.0.5 on 2020-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0025_minibanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvodstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('adress', models.CharField(blank=True, max_length=250, verbose_name='Адрес склада/производства')),
                ('phone', models.CharField(blank=True, max_length=18, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('yur_adress', models.CharField(blank=True, max_length=300, verbose_name='Юридический адрес')),
                ('inn', models.IntegerField(max_length=10)),
                ('date', models.DateField(verbose_name='Дата регистрации')),
                ('text1', models.TextField(verbose_name='Первая часть текста')),
                ('image1', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 1_1')),
                ('image2', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 1_2')),
                ('image3', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 1_3')),
                ('text2', models.TextField(verbose_name='Вторая часть текста')),
                ('image4', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 2_1')),
                ('image5', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 2_2')),
                ('image6', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 2_3')),
                ('text3', models.TextField(blank=True, verbose_name='Третья часть текста')),
                ('image7', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 3_1')),
                ('image8', models.ImageField(blank=True, upload_to='about_us', verbose_name='Изображение 3_2')),
                ('cert_image1', models.ImageField(blank=True, upload_to='about_us', verbose_name='Сертификат 1')),
                ('cert_file1', models.FileField(blank=True, upload_to='about_us', verbose_name='Файл серификата 1')),
                ('cert_image2', models.ImageField(blank=True, upload_to='about_us', verbose_name='Сертификат 2')),
                ('cert_file2', models.FileField(blank=True, upload_to='about_us', verbose_name='Файл серификата 2')),
                ('cert_image3', models.ImageField(blank=True, upload_to='about_us', verbose_name='Сертификат 3')),
                ('cert_file3', models.FileField(blank=True, upload_to='about_us', verbose_name='Файл серификата 3')),
                ('proizvodstva', models.ManyToManyField(blank=True, to='obuv.Proizvodstvo', verbose_name='Склады и производства')),
            ],
        ),
    ]
