# Generated by Django 3.0.5 on 2020-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0026_auto_20200506_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='proizvodstvo',
            options={'verbose_name': 'Производсто/Склад', 'verbose_name_plural': 'Производства/Склады'},
        ),
        migrations.AlterField(
            model_name='about',
            name='inn',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
