# Generated by Django 3.0.5 on 2020-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0027_auto_20200507_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='about_us', verbose_name='Основноре фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='about',
            name='inn',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='ИНН'),
        ),
    ]
