# Generated by Django 3.0.5 on 2020-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0028_auto_20200507_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='ИНН'),
        ),
    ]
