# Generated by Django 3.0.5 on 2020-05-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0029_auto_20200512_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='art_title',
        ),
    ]
