# Generated by Django 3.0.5 on 2020-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuv', '0030_auto_20200512_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='articles', verbose_name='Изображение на главной'),
        ),
    ]
